### ISSUE TITLE
Avoid versioning of generated files

### ISSUE THREAD

**Issue by amarlankri** [rescript-lang/rescript-project-template#1]
Hello,

Thanks for this project template!

I think `src/Demo.bs.js` should not be versioned as it is a file generated by `bsb`. In addition, `.gitignore` should be changed to prevent from versioning these generated files.

**Comment by chenglou** [comment]
Hello! The checking in of the artifact is recommended actually. Allows consuming our libs from JS, and allows output diffing, as per our [conversion guide](https://rescript-lang.org/docs/manual/latest/converting-from-js). Also helps checking that your `external` changes were done appropriately.
